### ISSUE TITLE
[버그] 봇 관리하기 페이지에서 지원 서버 입력란 튀어나감

### ISSUE THREAD

**Issue by comjun04** [koreanbots/koreanbots#68]
## 재현방법
* 모바일에서 자신의 봇 관리 페이지로 들어갑니다. (koreanbots.dev/**manage/xxx**)
* **지원 디스코드 서버** 입력란을 살펴봅니다.

## 예상되는 정상적인 동작
입력칸이 화면 내에 들어와 있어야 합니다.

## 발생한 문제
오른쪽으로 튀어나갑니다.
![Screenshot_2020-06-14-12-42-07](https://user-images.githubusercontent.com/30339539/84584273-2da13880-ae3d-11ea-8521-90d9348a8bab.png)

## 클라이언트 버전
v1.1.0 koreanbots/client@39e5d33

## 사양
Android 8.0 (Oreo)
Chrome 83.0.4103.101 (Mobile)

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
`CR`

![image](https://user-images.githubusercontent.com/31924512/84993692-9281c900-b184-11ea-8228-dcdab9553792.png)

**Comment by SaidBySolo** [comment]
CNR
In Samsung Galaxy S7 Android 8.0.0

[빌드정보] 버전: 1.1.0 해시: 0351b0bedc7c0b1ca8486468bf7aa23cc54ea003

![Screenshot_20200628-232314_Chrome](https://user-images.githubusercontent.com/33891531/85950231-8cff5c80-b996-11ea-8837-e5d76fa23b10.jpg)

**Comment by wonderlandpark** [comment]
지금보니까 기기 정보를 써주시면 좋을거 같네요. `Client Specific` 일 수도 있어서요.

**Comment by wonderlandpark** [comment]
`CNR` 제가 분명 고친기억은 없는데 고쳐져있네요

**Comment by SaidBySolo** [comment]
CNR In

https://github.com/koreanbots/koreanbots/issues/68#issuecomment-650768351

https://github.com/koreanbots/koreanbots/issues/68#issuecomment-650769326

Unfortunately, this issue was rejected because it was not reproduced.
If it is still reproducible, please reopen the issue

붛행히도 이 이슈는 재현되지않아 거부되었습니다.
여전히 재현이 가능하다면 다시 이슈를 열어주세요
